version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:466588010112:task-definition/currency-exchange-td:1"
        LoadBalancerInfo:
          ContainerName: "hello-world-rest-api"
          ContainerPort: "80"
        PlatformVersion: "LATEST"